### PR TITLE
Minor compilation fix

### PR DESCRIPTION
**Pull request by maikmerten**
add -lm to linker flags to fix a "undefined reference to symbol 'cos@…@GLIBC_2.2.5'" compile error

Compiles and works on Xubuntu 15.04 now.

### CODE REVIEW

**Comment by robn** [comment]
I didn't check this myself, taking your word for it. Very curious to know what you're doing with this; I haven't thought about it for many years!

**Comment by maikmerten** [comment]
Thanks for merging :)

I'm interested in compact SID emulation engines that a) sound "close enough" and b) may fit into a microcontroller to serve as a drop-in replacement for an actual SID chip.

With SwinSID http://www.swinkels.tvtom.pl/swinsid/ there is already such a product available (and I own two of those). SwinSID is based on overclocked Atmega 8-bit microcontrollers and tightly written assembler code to read bus signals and to synthesize sound. After some hiatus, new and improved versions are available over at http://www.amibay.com/showthread.php?68521-nano-SwinSID-HC-%28High-Compatibility%29

However, I suspect that modern 32-bit microcontrollers (ARM-based like stm32 or MIPS-based like the pic32 family) may offer a more flexible platform with much improved computational headroom, that allows for, e.g., more precise emulation all while being programmed in C (for better portability and increased development speed). I'd also like the firmware to be free software (in the sense of "libre").

It indeed appears that TinySid works rather nicely on microcontrollers (and your project apparently was already forked on GitHub for stm32 and pic32 controllers):
https://www.youtube.com/watch?v=ZNu0-MZ9WLI
https://www.youtube.com/watch?v=qlF1tdN5dK4

Instead of emulating the CPU and VIC-II a drop-in solution would instead have to listen to the system bus instead, of course.

Now, after having said all this, I don't currently have the necessary microcontroller experience to actually pull ahead and just "do it". However, I like having some pieces of the puzzle sorted out beforehand, which is why I wanted TinySid to compile on my machine to listen to some SID tunes. I find that some tunes sound really nice (yay!), while other tunes seem to trigger bugs with the noise generator. No matter what, TinySid looks like a nice place to start from :)

**Comment by robn** [comment]
Interesting links, thanks!

Fyi, I started working on it because I wanted to run it on the Nintendo DS' secondary CPU (ARM7). I got SIDPlayer mostly working but its performance was awful with floating-point emulation. I never did quite get this to a point where I was happy with the output for most test cases and I sort of got stuck after that - I'm not hugely familiar with the SIDs internals and I'm pretty terrible at the required math :)

Good luck!

**Comment by maikmerten** [comment]
After digging around a bit I also find that Rockbox includes SID emulation based on TinySid:

http://git.rockbox.org/?p=rockbox.git;a=blob;f=lib/rbcodec/codecs/sid.c;hb=HEAD

This version has several interesting improvements:
- seems to have fixed a problem where the noise channel just wouldn't stop playing (e.g., Lightforce)
- much improved timing (for instance, Driller would play too fast)
- all-integer computation (your Nintendo DS may like that a lot)

Overall very nice. I assume it may make sense to rebase on that.
